load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "log",
    srcs = ["log.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "parallel",
    srcs = ["parallel.py"],
    imports = [".."],
    visibility = ["//visibility:public"],
)
