load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "storage",
    srcs = [
        "feature_store.py",
        "price_store.py",
        "universe_store.py",
    ],
    imports = ["../.."],
    deps = [
        "@pypi//pandas",
        "@pypi//pyarrow",
    ],
    visibility = ["//visibility:public"],
)
