load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "ingestion",
    srcs = ["yfinance_client.py"],
    imports = ["../.."],
    deps = [
        "@pypi//pandas",
        "@pypi//yfinance",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "main",
    srcs = ["main.py"],
    imports = ["../.."],
    deps = [
        ":ingestion",
        "//python/stock_picker/storage",
        "//python/stock_picker/tickers",
        "@pypi//yfinance",
    ],
)
