# gazelle:python_generation_mode file
load("//bazel/rules/pytest:defs.bzl", "py_pytest")

py_pytest(
    name = "test_backtest",
    srcs = ["test_backtest.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_dataset",
    srcs = ["test_dataset.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_splits",
    srcs = ["test_splits.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_model",
    srcs = ["test_model.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//numpy",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_train",
    srcs = ["test_train.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//numpy",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_inference",
    srcs = ["test_inference.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_importance",
    srcs = ["test_importance.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//numpy",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_ensemble",
    srcs = ["test_ensemble.py"],
    imports = ["../../.."],
    deps = [
        "//python/stock_picker/training",
        "@pypi//numpy",
        "@pypi//pandas",
    ],
)

py_pytest(
    name = "test_job",
    srcs = ["test_job.py"],
    imports = ["../../.."],
    deps = ["//python/stock_picker/training"],
)
