load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "tickers",
    srcs = [
        "manual_additions.py",
        "universe.py",
    ],
    imports = ["../.."],
    deps = [
        "@pypi//lxml",
        "@pypi//pandas",
        "@pypi//requests",
    ],
    visibility = ["//visibility:public"],
)
